# Generated by Django 6.1 on 2026-09-23 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha_evento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha evento'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='anonima',
            field=models.BooleanField(default=False, verbose_name='Anónima'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha cierre'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='privacidad',
            field=models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=20, verbose_name='Privacidad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha envío'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='fecha_uso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha uso'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='invitacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=150, verbose_name='Opción'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='valor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='completada',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='estado',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('completada', 'Completada'), ('abandonada', 'Abandonada')], default='iniciada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('creador', 'Creador'), ('participante', 'Participante')], default='participante', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='obligatoria',
            field=models.BooleanField(default=True, verbose_name='Obligatoria'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=255, verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto_corto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('opcion_unica', 'Opción única'), ('opcion_multiple', 'Opción múltiple'), ('si_no', 'Sí / No'), ('escala', 'Escala')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha respuesta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_booleano',
            field=models.BooleanField(blank=True, null=True, verbose_name='Respuesta Sí / No'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_numero',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Respuesta número'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta_texto',
            field=models.TextField(blank=True, verbose_name='Respuesta texto'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualización'),
        ),
    ]
